name: CI Kifiya_AI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3 # Checks out your repository
    - name: Set up Python # Sets up the Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies # Installs the project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Kifiya_AI # Runs the project's tests
      run: |
        python -m unittest discover tests
